### ISSUE TITLE
Not all hermes.* topics ingested?

### ISSUE THREAD

**Issue by phycodurus** [LCOGT/hermes#23]
Messages submitted to `hermes.message` topic don't show up in Browse list.
`hermes.test` topic is working, however. I've not tested other topics like `hermes.photometry`, etc.

To reproduce:
1. login to Hermes and go to Submit Message pane
2. fill out Title, specify `hermes.message` in Topic drop-down, Submit.

Expected result: new message in Browse pane (to which you are re-directed)
Observed result: no new message.

**Comment by jchate6** [comment]
I have found this for everything but hermes.test

**Comment by jnation3406** [comment]
This is because hermes is currently configured to only ingest 3 specific topics. We can redeploy with it configured for more topics whenever we want...
