### ISSUE TITLE
Originally ingested Kafka message not readily available

### ISSUE THREAD

**Issue by phycodurus** [LCOGT/hermes#25]
Hermes provides views of ingested messages after parsing, but sometimes I'd like to see the original message as it was received from the Kafka stream. (and the "message_text" field does not seem to be that, if I'm not mistaken).

**Comment by jnation3406** [comment]
Can you elaborate on this more, maybe link to a message that doesn't have the original data you want and point to what is missing? Depending on which stream the message is being ingested from, it can have a different format - in some cases the format is plain text and in others it is more of an object with structured data. In the case that it is an object, we map what we can to the message information like the title/authors/submitter and then the message itself either into message_text (if it is just a big text blob) or into the data JSONField (if it is structured data). We may add additional key/value pairs of metadata into the data field in this case, such as the "area50" and "area90" fields into a LVC notice.

**Comment by jchate6** [comment]
Might be the same as or related to issue [#31](https://github.com/LCOGT/hermes-frontend/issues/31)
