### ISSUE TITLE
Update GCN parsing to include new schema

### ISSUE THREAD

**Issue by jchate6** [LCOGT/hermes#26]
See general info [here](https://emfollow.docs.ligo.org/userguide/content.html)
and Kafka details [here](https://emfollow.docs.ligo.org/userguide/content.html#kafka)

Specifically, the `event.significant` key/value seems... significant.

**Comment by jnation3406** [comment]
We need to figure out what if anything will be changing in the gcn classic over kafka format for this data, since their format is different from the official format.

**Comment by jnation3406** [comment]
This was finished a few months ago, closing.
