### ISSUE TITLE
Topics pull down does not reflect ingested topics

### ISSUE THREAD

**Issue by phycodurus** [LCOGT/hermes#33]
This is in the `dev` deployment. After deploying the fix to Issue #23, and submitting a [message](http://hermes-dev.lco.gtn/message/c8aaacbe-db51-4e65-868d-480962d419bc) to to `hermes.discovery` topic, I expect, after the messages was ingested, that the `hermes.discovery` topic be available in the Topic filter pull down of the Browse Tab, but it's missing.

**Comment by jnation3406** [comment]
This was fixed in the May in v1.0
