### ISSUE TITLE
Fix Django-restframe CSS

### ISSUE THREAD

**Issue by jchate6** [LCOGT/hermes#36]
For some reason the django restframe css is... missing? Something wonky there. we should get that cleaned up.

**Comment by manning-ncsa** [comment]
If you are talking about how to get a page like https://hermes.lco.global/api/v0/profile/ to render properly, I encountered a similar issue when configuring our recent "archive API" (a.k.a. "a completely redundant subset of Hermes"...) Django app deployment for "production" as the Django docs describe. The [section about static files](https://docs.djangoproject.com/en/4.1/howto/static-files/deployment/) led me to [a `deployment.yaml` that looks like this](https://github.com/scimma/archive-ingest/blob/78f2ed68b88fda67ea75be2310c9b534823b3820/kubernetes/charts/hop-archive-system/templates/deployment.yaml), where the "collect static" stage is an initContainer that stores assets in a shared `emptyDir` volume between containers in the pod, one of which is [an NGINX container that actually serves them](https://github.com/scimma/archive-ingest/blob/78f2ed68b88fda67ea75be2310c9b534823b3820/kubernetes/charts/hop-archive-system/templates/configmap.yaml#L140-L185).

**Comment by jnation3406** [comment]
This has been fixed for a while now.
